CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    max_weight DECIMAL(2,1) NOT NULL,
    last_interaction TIMESTAMP NOT NULL
);
create index user_actions_user_id_event_id_index on user_actions (user_id, event_id);

CREATE TABLE IF NOT EXISTS event_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score REAL NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
create index event_similarities_event_a_index on event_similarities (event_a);
create index event_similarities_event_b_index on event_similarities (event_b);