DROP TABLE IF EXISTS event_comments CASCADE;

CREATE TABLE IF NOT EXISTS event_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    text VARCHAR(7000),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT pk_event_comments PRIMARY KEY (id)
);
create index event_comments_id_index on event_comments (id);
create index event_comments_event_id_index on event_comments (event_id);
create index event_comments_author_id_index on event_comments (author_id);
create index event_comments_status_index on event_comments (status);