DROP TABLE IF EXISTS event_requests CASCADE;

CREATE TABLE IF NOT EXISTS event_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT pk_event_requests PRIMARY KEY (id)
);
create index event_requests_event_id_index on event_requests (event_id);
create index event_requests_status_index on event_requests (status);