spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:6432/ewm-stats
    driver-class-name: org.postgresql.Driver
server:
  port: 9090